export const sellerHelp = {
    "Open an account": [
      { title: "Why choose Gumroad?", slug: "64-is-gumroad-for-me" },
      { title: "Account settings", slug: "67-the-settings-menu" },
      { title: "Filling out payout settings", slug: "260-your-payout-settings-page" },
      { title: "Build a website on Gumroad", slug: "124-your-gumroad-profile-page" },
      { title: "Having multiple accounts", slug: "252-multiple-accounts" },
      { title: "Protecting creator privacy", slug: "120-protecting-your-privacy-on-gumroad" },
      { title: "Account login security", slug: "292-account-login-security" },
      { title: "Things not allowed on Gumroad", slug: "155-things-you-cant-sell-on-gumroad" },
      { title: "Selling services", slug: "70-can-i-sell-services" },
      { title: "Adult content on Gumroad", slug: "156-gumroad-and-adult-content" },
      { title: "Deleting a Gumroad account", slug: "37-how-to-delete-your-gumroad-account" }
    ],
    "Add a product": [
      { title: "The products dashboard", slug: "304-products-dashboard" },
      { title: "Adding a product", slug: "149-adding-a-product" },
      { title: "Adding cover and thumbnail images", slug: "60-adding-a-cover-image" },
      { title: "Checkout customization", slug: "101-designing-your-product-page" },
      { title: "Custom product URLs", slug: "81-custom-product-urls" },
      { title: "Unpublish or delete a product", slug: "248-delete-a-product" },
      { title: "Setting up versions", slug: "126-setting-up-versions-on-a-digital-product" },
      { title: "Selling physical products", slug: "85-physical-products" },
      { title: "Using Gumroad and Printful", slug: "172-using-gumroad-and-printful" },
      { title: "Selling memberships", slug: "82-membership-products" },
      { title: "\"Pay what you want\" pricing", slug: "133-pay-what-you-want-pricing" },
      { title: "Prepare videos for streaming", slug: "43-streaming-videos" },
      { title: "Compress videos using Handbrake", slug: "125-how-to-compress-a-video-using-handbrake" },
      { title: "Mobile-friendly files", slug: "112-mobile-friendly-files" },
      { title: "Metadata for audio files", slug: "176-metadata-for-audio-files" },
      { title: "Becoming an affiliate on Gumroad", slug: "249-affiliate-faq" },
      { title: "File size limits", slug: "289-file-size-limits-on-gumroad" },
      { title: "Product bundles", slug: "339-product-bundles" },
      { title: "Collaborate with another creator", slug: "341-collaborations" }
    ],
    "Start selling": [
      { title: "Testing a purchase", slug: "62-testing-a-purchase" },
      { title: "Gumroad Discover", slug: "79-gumroad-discover" },
      { title: "Find a product's URL", slug: "136-find-your-products-url" },
      { title: "The sales dashboard", slug: "268-customer-dashboard" },
      { title: "The sales analytics dashboard", slug: "74-the-analytics-dashboard" },
      { title: "How Gumroad works for customers", slug: "282-how-do-purchases-work-for-my-customers" },
      { title: "The Gumroad Library", slug: "247-what-your-customers-see" },
      { title: "Gumroad mobile app", slug: "177-the-gumroad-dashboard-app" },
      { title: "Why customer payments fail", slug: "266-why-are-my-customers-purchases-failing" },
      { title: "Customers not receiving receipts", slug: "78-my-customer-did-not-receive-a-receipt" },
      { title: "Cancel customer memberships", slug: "139-how-to-cancel-your-customers-subscriptions" },
      { title: "Issuing a refund", slug: "47-how-to-refund-a-customer" },
      { title: "Chargebacks on Gumroad", slug: "134-how-does-gumroad-handle-chargebacks" },
      { title: "Content protection on Gumroad", slug: "42-content-security" },
      { title: "Purchasing Power Parity", slug: "327-purchasing-power-parity" },
      { title: "Creating an Upsell", slug: "331-creating-upsells" },
      { title: "More like this", slug: "334-more-like-this" },
      { title: "Set a custom refund policy", slug: "335-custom-refund-policy" },
      { title: "Product bundles", slug: "339-product-bundles" }
    ],
    "Market your work": [
      { title: "Starting an email newsletter", slug: "170-audience" },
      { title: "Send email updates", slug: "169-how-to-send-an-update" },
      { title: "Send automated emails with Workflows", slug: "131-using-workflows-to-send-automated-updates" },
      { title: "Customers not receiving emails", slug: "54-not-receiving-updates" },
      { title: "Integrating Gumroad into websites", slug: "44-build-gumroad-into-your-website" },
      { title: "Affiliates on Gumroad", slug: "333-affiliates-on-gumroad" },
      { title: "Product bundles", slug: "339-product-bundles" }
    ],
    "Get paid": [
      { title: "Getting paid by Gumroad", slug: "13-getting-paid" },
      { title: "Connect your Stripe account to Gumroad", slug: "330-stripe-connect" },
      { title: "Adding PayPal to checkout", slug: "275-paypal-connect" },
      { title: "Gumroad's fees", slug: "66-gumroads-fees" },
      { title: "The payouts dashboard", slug: "269-balance-page" },
      { title: "Payoneer, Transferwise, and Gumroad", slug: "223-payoneer-and-gumroad" },
      { title: "What currency does Gumroad use?", slug: "46-what-currency-does-gumroad-use" },
      { title: "Payout delays", slug: "281-payout-delays" },
      { title: "Sales tax on Gumroad", slug: "121-sales-tax-on-gumroad" },
      { title: "US sales tax on Gumroad", slug: "11-us-sales-tax-on-gumroad" },
      { title: "EU & UK VAT on Gumroad", slug: "10-dealing-with-vat" },
      { title: "Australian GST on Gumroad", slug: "96-australian-gst-on-gumroad" },
      { title: "Indirect taxes on sales via Gumroad Discover", slug: "325-indirect-taxes-on-sales-via-discover" },
      { title: "Does Gumroad issue form 1099-K and 1099-MISC?", slug: "15-1099s" },
      { title: "Account suspension FAQ", slug: "160-suspension" },
      { title: "Fraudulent purchases", slug: "283-fraudulent-purchases" },
      { title: "Defining fraud on Gumroad", slug: "161-what-gumroad-considers-fraud" },
      { title: "Singaporean GST on Gumroad", slug: "336-singaporean-gst" }
    ],
    "Advanced": [
      { title: "Discount codes", slug: "128-discount-codes" },
      { title: "Teams and Roles", slug: "326-teams-and-roles" },
      { title: "PDF stamping", slug: "130-pdf-stamping" },
      { title: "Facebook domain verification", slug: "290-facebook-domain-verification" },
      { title: "Product ratings and reviews", slug: "222-product-ratings-on-gumroad" },
      { title: "Send customers to the payment form", slug: "144-send-customers-directly-to-your-payment-form" },
      { title: "URL parameters", slug: "270-url-parameters" },
      { title: "Setting up a custom domain", slug: "153-setting-up-a-custom-domain" },
      { title: "Third-party analytics", slug: "174-third-party-analytics" },
      { title: "Turn off third-party trackers", slug: "285-turning-off-third-party-trackers" },
      { title: "Integrating products with external services", slug: "295-external-integration" },
      { title: "Zapier integrations with Gumroad", slug: "107-common-zapier-integrations-with-gumroad" },
      { title: "Create an application for the API", slug: "280-create-application-api" },
      { title: "License keys", slug: "76-license-keys" },
      { title: "Accessibility statement for Gumroad", slug: "324-accessibiility-statement" },
      { title: "Customer Moderation", slug: "329-customer-moderation" }
    ],
    "Contact Gumroad": [
      { title: "Contact Gumroad", slug: "20-how-do-i-contact-gumroad" },
      { title: "Gumroad's refund policy", slug: "51-what-is-gumroads-refund-policy" },
      { title: "Report a Gumroad creator", slug: "286-how-do-i-report-a-gumroad-creator" },
      { title: "DMCA counter notices", slug: "288-dmca-counter-notices" },
      { title: "Gumroad's subprocessors", slug: "110-gumroads-subprocessors" },
      { title: "Supported browsers", slug: "53-what-browsers-does-gumroad-support" },
      { title: "Jobs at Gumroad", slug: "284-jobs-at-gumroad" }
    ],
  }
  
  export const customerHelp = {
    "Before you buy": ["Article 1", "Article 2"],
    "Accessing your purchase": ["Article 1", "Article 2"],
    "Receipts and refunds": ["Article 1", "Article 2"],
    "Issues with your purchase": ["Article 1", "Article 2"],
  }
  
  export const savedReplies = [
    { title: "Reply 1", content: "This is the full text of Reply 1. It can be quite long and detailed." },
    { title: "Reply 2", content: "Here's the complete content of Reply 2. It might include formatting or multiple paragraphs." },
    { title: "Reply 3", content: "Reply 3 full text goes here. It could contain instructions, explanations, or any other relevant information." }
  ]