export const sellerHelp = {
    "Open an account": [
      { title: "Why choose Gumroad?", url: "https://help.gumroad.com/article/64-is-gumroad-for-me.html" },
      { title: "Account settings", url: "https://help.gumroad.com/article/67-the-settings-menu.html" },
      { title: "Filling out payout settings", url: "https://help.gumroad.com/article/260-your-payout-settings-page.html" },
      { title: "Build a website on Gumroad", url: "https://help.gumroad.com/article/124-your-gumroad-profile-page.html" },
      { title: "Having multiple accounts", url: "https://help.gumroad.com/article/252-multiple-accounts.html" },
      { title: "Protecting creator privacy", url: "https://help.gumroad.com/article/120-protecting-your-privacy-on-gumroad.html" },
      { title: "Account login security", url: "https://help.gumroad.com/article/292-account-login-security.html" },
      { title: "Things not allowed on Gumroad", url: "https://help.gumroad.com/article/155-things-you-cant-sell-on-gumroad.html" },
      { title: "Selling services", url: "https://help.gumroad.com/article/70-can-i-sell-services.html" },
      { title: "Adult content on Gumroad", url: "https://help.gumroad.com/article/156-gumroad-and-adult-content.html" },
      { title: "Deleting a Gumroad account", url: "https://help.gumroad.com/article/37-how-to-delete-your-gumroad-account.html" }
    ],
    "Add a product": [
      { title: "The products dashboard", url: "https://help.gumroad.com/article/304-products-dashboard.html" },
      { title: "Adding a product", url: "https://help.gumroad.com/article/149-adding-a-product.html" },
      { title: "Adding cover and thumbnail images", url: "https://help.gumroad.com/article/60-adding-a-cover-image.html" },
      { title: "Checkout customization", url: "https://help.gumroad.com/article/101-designing-your-product-page.html" },
      { title: "Custom product URLs", url: "https://help.gumroad.com/article/81-custom-product-urls.html" },
      { title: "Unpublish or delete a product", url: "https://help.gumroad.com/article/248-delete-a-product.html" },
      { title: "Setting up versions", url: "https://help.gumroad.com/article/126-setting-up-versions-on-a-digital-product.html" },
      { title: "Selling physical products", url: "https://help.gumroad.com/article/85-physical-products.html" },
      { title: "Using Gumroad and Printful", url: "https://help.gumroad.com/article/172-using-gumroad-and-printful.html" },
      { title: "Selling memberships", url: "https://help.gumroad.com/article/82-membership-products.html" },
      { title: "\"Pay what you want\" pricing", url: "https://help.gumroad.com/article/133-pay-what-you-want-pricing.html" },
      { title: "Prepare videos for streaming", url: "https://help.gumroad.com/article/43-streaming-videos.html" },
      { title: "Compress videos using Handbrake", url: "https://help.gumroad.com/article/125-how-to-compress-a-video-using-handbrake.html" },
      { title: "Mobile-friendly files", url: "https://help.gumroad.com/article/112-mobile-friendly-files.html" },
      { title: "Metadata for audio files", url: "https://help.gumroad.com/article/176-metadata-for-audio-files.html" },
      { title: "Becoming an affiliate on Gumroad", url: "https://help.gumroad.com/article/249-affiliate-faq.html" },
      { title: "File size limits", url: "https://help.gumroad.com/article/289-file-size-limits-on-gumroad.html" },
      { title: "Product bundles", url: "https://help.gumroad.com/article/339-product-bundles.html" },
      { title: "Collaborate with another creator", url: "https://help.gumroad.com/article/341-collaborations.html" }
    ],
    "Start selling": [
      { title: "Testing a purchase", url: "https://help.gumroad.com/article/62-testing-a-purchase.html" },
      { title: "Gumroad Discover", url: "https://help.gumroad.com/article/79-gumroad-discover.html" },
      { title: "Find a product's URL", url: "https://help.gumroad.com/article/136-find-your-products-url.html" },
      { title: "The sales dashboard", url: "https://help.gumroad.com/article/268-customer-dashboard.html" },
      { title: "The sales analytics dashboard", url: "https://help.gumroad.com/article/74-the-analytics-dashboard.html" },
      { title: "How Gumroad works for customers", url: "https://help.gumroad.com/article/282-how-do-purchases-work-for-my-customers.html" },
      { title: "The Gumroad Library", url: "https://help.gumroad.com/article/247-what-your-customers-see.html" },
      { title: "Gumroad mobile app", url: "https://help.gumroad.com/article/177-the-gumroad-dashboard-app.html" },
      { title: "Why customer payments fail", url: "https://help.gumroad.com/article/266-why-are-my-customers-purchases-failing.html" },
      { title: "Customers not receiving receipts", url: "https://help.gumroad.com/article/78-my-customer-did-not-receive-a-receipt.html" },
      { title: "Cancel customer memberships", url: "https://help.gumroad.com/article/139-how-to-cancel-your-customers-subscriptions.html" },
      { title: "Issuing a refund", url: "https://help.gumroad.com/article/47-how-to-refund-a-customer.html" },
      { title: "Chargebacks on Gumroad", url: "https://help.gumroad.com/article/134-how-does-gumroad-handle-chargebacks.html" },
      { title: "Content protection on Gumroad", url: "https://help.gumroad.com/article/42-content-security.html" },
      { title: "Purchasing Power Parity", url: "https://help.gumroad.com/article/327-purchasing-power-parity.html" },
      { title: "Creating an Upsell", url: "https://help.gumroad.com/article/331-creating-upsells.html" },
      { title: "More like this", url: "https://help.gumroad.com/article/334-more-like-this.html" },
      { title: "Set a custom refund policy", url: "https://help.gumroad.com/article/335-custom-refund-policy.html" },
      { title: "Product bundles", url: "https://help.gumroad.com/article/339-product-bundles.html" }
    ],
    "Market your work": [
      { title: "Starting an email newsletter", url: "https://help.gumroad.com/article/170-audience.html" },
      { title: "Send email updates", url: "https://help.gumroad.com/article/169-how-to-send-an-update.html" },
      { title: "Send automated emails with Workflows", url: "https://help.gumroad.com/article/131-using-workflows-to-send-automated-updates.html" },
      { title: "Customers not receiving emails", url: "https://help.gumroad.com/article/54-not-receiving-updates.html" },
      { title: "Integrating Gumroad into websites", url: "https://help.gumroad.com/article/44-build-gumroad-into-your-website.html" },
      { title: "Affiliates on Gumroad", url: "https://help.gumroad.com/article/333-affiliates-on-gumroad.html" },
      { title: "Product bundles", url: "https://help.gumroad.com/article/339-product-bundles.html" }
    ],
    "Get paid": [
      { title: "Getting paid by Gumroad", url: "https://help.gumroad.com/article/13-getting-paid.html" },
      { title: "Connect your Stripe account to Gumroad", url: "https://help.gumroad.com/article/330-stripe-connect.html" },
      { title: "Adding PayPal to checkout", url: "https://help.gumroad.com/article/275-paypal-connect.html" },
      { title: "Gumroad's fees", url: "https://help.gumroad.com/article/66-gumroads-fees.html" },
      { title: "The payouts dashboard", url: "https://help.gumroad.com/article/269-balance-page.html" },
      { title: "Payoneer, Transferwise, and Gumroad", url: "https://help.gumroad.com/article/223-payoneer-and-gumroad.html" },
      { title: "What currency does Gumroad use?", url: "https://help.gumroad.com/article/46-what-currency-does-gumroad-use.html" },
      { title: "Payout delays", url: "https://help.gumroad.com/article/281-payout-delays.html" },
      { title: "Sales tax on Gumroad", url: "https://help.gumroad.com/article/121-sales-tax-on-gumroad.html" },
      { title: "US sales tax on Gumroad", url: "https://help.gumroad.com/article/11-us-sales-tax-on-gumroad.html" },
      { title: "EU & UK VAT on Gumroad", url: "https://help.gumroad.com/article/10-dealing-with-vat.html" },
      { title: "Australian GST on Gumroad", url: "https://help.gumroad.com/article/96-australian-gst-on-gumroad.html" },
      { title: "Indirect taxes on sales via Gumroad Discover", url: "https://help.gumroad.com/article/325-indirect-taxes-on-sales-via-discover.html" },
      { title: "Does Gumroad issue form 1099-K and 1099-MISC?", url: "https://help.gumroad.com/article/15-1099s.html" },
      { title: "Account suspension FAQ", url: "https://help.gumroad.com/article/160-suspension.html" },
      { title: "Fraudulent purchases", url: "https://help.gumroad.com/article/283-fraudulent-purchases.html" },
      { title: "Defining fraud on Gumroad", url: "https://help.gumroad.com/article/161-what-gumroad-considers-fraud.html" },
      { title: "Singaporean GST on Gumroad", url: "https://help.gumroad.com/article/336-singaporean-gst.html" }
    ],
    "Advanced": [
      { title: "Discount codes", url: "https://help.gumroad.com/article/128-discount-codes.html" },
      { title: "Teams and Roles", url: "https://help.gumroad.com/article/326-teams-and-roles.html" },
      { title: "PDF stamping", url: "https://help.gumroad.com/article/130-pdf-stamping.html" },
      { title: "Facebook domain verification", url: "https://help.gumroad.com/article/290-facebook-domain-verification.html" },
      { title: "Product ratings and reviews", url: "https://help.gumroad.com/article/222-product-ratings-on-gumroad.html" },
      { title: "Send customers to the payment form", url: "https://help.gumroad.com/article/144-send-customers-directly-to-your-payment-form.html" },
      { title: "URL parameters", url: "https://help.gumroad.com/article/270-url-parameters.html" },
      { title: "Setting up a custom domain", url: "https://help.gumroad.com/article/153-setting-up-a-custom-domain.html" },
      { title: "Third-party analytics", url: "https://help.gumroad.com/article/174-third-party-analytics.html" },
      { title: "Turn off third-party trackers", url: "https://help.gumroad.com/article/285-turning-off-third-party-trackers.html" },
      { title: "Integrating products with external services", url: "https://help.gumroad.com/article/295-external-integration.html" },
      { title: "Zapier integrations with Gumroad", url: "https://help.gumroad.com/article/107-common-zapier-integrations-with-gumroad.html" },
      { title: "Create an application for the API", url: "https://help.gumroad.com/article/280-create-application-api.html" },
      { title: "License keys", url: "https://help.gumroad.com/article/76-license-keys.html" },
      { title: "Accessibility statement for Gumroad", url: "https://help.gumroad.com/article/324-accessibiility-statement.html" },
      { title: "Customer Moderation", url: "https://help.gumroad.com/article/329-customer-moderation.html" }
    ],
    "Contact Gumroad": [
      { title: "Contact Gumroad", url: "https://help.gumroad.com/article/20-how-do-i-contact-gumroad.html" },
      { title: "Gumroad's refund policy", url: "https://help.gumroad.com/article/51-what-is-gumroads-refund-policy.html" },
      { title: "Report a Gumroad creator", url: "https://help.gumroad.com/article/286-how-do-i-report-a-gumroad-creator.html" },
      { title: "DMCA counter notices", url: "https://help.gumroad.com/article/288-dmca-counter-notices.html" },
      { title: "Gumroad's subprocessors", url: "https://help.gumroad.com/article/110-gumroads-subprocessors.html" },
      { title: "Supported browsers", url: "https://help.gumroad.com/article/53-what-browsers-does-gumroad-support.html" },
      { title: "Jobs at Gumroad", url: "https://help.gumroad.com/article/284-jobs-at-gumroad.html" }
    ],
  }
  
  export const customerHelp = {
    "Before you buy": [
      { title: "A guide to buying on Gumroad", url: "https://customers.gumroad.com/article/191-a-guide-to-buying-on-gumroad.html" },
      { title: "How do I give a product as a gift?", url: "https://customers.gumroad.com/article/213-how-do-i-give-a-product-as-a-gift.html" },
      { title: "Why did my payment fail?", url: "https://customers.gumroad.com/article/203-why-did-my-payment-fail.html" },
      { title: "Safe buying on Gumroad", url: "https://customers.gumroad.com/article/189-safe-gumroad-buying.html" },
      { title: "Wishlists", url: "https://customers.gumroad.com/article/343-wishlists.html" },
    ],
    "Accessing your purchase": [
      { title: "How do I access my purchase?", url: "https://customers.gumroad.com/article/199-how-do-i-access-my-purchase.html" },
      { title: "Your Gumroad Library", url: "https://customers.gumroad.com/article/198-your-gumroad-library.html" },
      { title: "Guide to memberships", url: "https://customers.gumroad.com/article/278-guide-to-memberships.html" },
      { title: "How to open ZIP and RAR files", url: "https://customers.gumroad.com/article/206-how-to-open-zip-and-rar-files.html" },
      { title: "How do I send my purchases to Kindle?", url: "https://customers.gumroad.com/article/208-how-do-i-send-my-gumroad-purchase-to-my-kindle.html" },
      { title: "How do I send my purchase to Dropbox?", url: "https://customers.gumroad.com/article/210-send-your-purchase-to-dropbox.html" },
      { title: "When will my purchase be shipped?", url: "https://customers.gumroad.com/article/215-when-will-my-purchase-be-shipped.html" },
      { title: "Rate and review your purchase", url: "https://customers.gumroad.com/article/344-rate-and-review-your-purchase.html" },
    ],
    "Receipts and refunds": [
      { title: "Get to know your Gumroad receipt", url: "https://customers.gumroad.com/article/204-get-to-know-your-gumroad-receipt.html" },
      { title: "How do I get a refund?", url: "https://customers.gumroad.com/article/190-how-do-i-get-a-refund.html" },
      { title: "I need an invoice", url: "https://customers.gumroad.com/article/194-i-need-an-invoice.html" },
      { title: "I need a VAT refund", url: "https://customers.gumroad.com/article/200-i-need-a-vat-refund.html" },
      { title: "I never received a receipt", url: "https://customers.gumroad.com/article/212-i-never-received-a-receipt.html" },
    ],
    "Issues with your purchase": [
      { title: "There's an issue with my purchase", url: "https://customers.gumroad.com/article/195-theres-an-issue-with-my-purchase.html" },
      { title: "Why was I charged by Gumroad?", url: "https://customers.gumroad.com/article/214-why-was-i-charged-by-gumroad.html" },
      { title: "How do I cancel my membership?", url: "https://customers.gumroad.com/article/192-how-do-i-cancel-my-membership.html" },
      { title: "My purchase isn't downloading", url: "https://customers.gumroad.com/article/193-my-purchase-isnt-downloading.html" },
      { title: "I'm not receiving updates", url: "https://customers.gumroad.com/article/211-im-not-receiving-updates.html" },
      { title: "Combining multiple accounts", url: "https://customers.gumroad.com/article/209-how-do-i-combine-two-accounts.html" },
      { title: "Why do I have a $1 charge from Gumroad?", url: "https://customers.gumroad.com/article/197-why-do-i-have-a-1-charge-from-gumroad.html" },
      { title: "I have extra charges from Gumroad after my purchase", url: "https://customers.gumroad.com/article/217-i-have-extra-charges-from-gumroad-after-my-purchase.html" },
      { title: "How do I delete my credit card information?", url: "https://customers.gumroad.com/article/216-delete-credit-card-information.html" },
      { title: "Incorrect recurring charge", url: "https://customers.gumroad.com/article/251-incorrect-recurring-charge.html" },
      { title: "Report a Gumroad creator", url: "https://customers.gumroad.com/article/226-report-a-creator.html" },
      { title: "How do I contact Gumroad?", url: "https://customers.gumroad.com/article/196-contact-gumroad.html" },
    ],
  }
  
  export const savedReplies = [
    { title: "Reply 1", content: "This is the full text of Reply 1. It can be quite long and detailed." },
    { title: "Reply 2", content: "Here's the complete content of Reply 2. It might include formatting or multiple paragraphs." },
    { title: "Reply 3", content: "Reply 3 full text goes here. It could contain instructions, explanations, or any other relevant information." }
  ]